- eventType: buildSolution
  studentId: m4242
  topic: modeling
  term: "2018-10"
  task: mid_term
  gitUrl: "gitlab.com/alice/modeling"
  .eventNumber: 9

- eventType: gradeSolution
  studentId: m4242
  topic: modeling
  term: "2018-10"
  task: mid_term
  points: 20.0
  .eventNumber: 10

- eventType: buildSolution
  studentId: m4242
  topic: modeling
  term: "2018-10"
  task: finals
  gitUrl: "gitlab.com/alice/modeling"
  .eventNumber: 11

- eventType: gradeSolution
  studentId: m4242
  topic: modeling
  term: "2018-10"
  task: finals
  points: 40.0
  .eventNumber: 12

- eventType: examinationGraded
  studentId: m4242
  courseName: modeling
  date: "2018-10"
  lecturerName: Albert
  grade: A
  .eventNumber: 13

