  - eventType: buildSEGroup
  head: Albert
  .eventNumber: 1

- eventType: studentCreated
  studentId: m4242
  name: Alica
  .eventNumber: 2

- eventType: buildSEClass
  topic: modeling
  term: "2018-10"
  .eventNumber: 3

- eventType: buildAssignment
  topic: modeling
  term: "2018-10"
  task: mid_term
  points: 23.0
  .eventNumber: 4

- eventType: buildAssignment
  topic: modeling
  term: "2018-10"
  task: finals
  points: 42.0
  .eventNumber: 5

