- eventType: studentOfficeCreated
  name: FB16
  .eventKey: studentOfficeCreated
  .eventNumber: 1

- eventType: studyProgramCreated
  name: CS
  .eventNumber: 2

- eventType: courseCreated
  programName: CS
  name: math
  .eventNumber: 3

- eventType: courseCreated
  programName: CS
  name: modeling
  .eventNumber: 4

- eventType: lecturerCreated
  name: Albert
  .eventNumber: 5

- eventType: examinationCreated
  course: modeling
  lecturer: Albert
  date: "2019-03-19"
  .eventNumber: 6

- eventType: studentCreated
  studentId: m2323
  name: Bob
  .eventKey: "studentCreated/m2323"
  .eventNumber: 8

- eventType: studentCreated
  studentId: m4242
  name: Alice
  .eventKey: "studentCreated/m4242"
  .eventNumber: 9

- eventType: chooseMajorSubject
  studentId: m4242
  majorSubject: CS
  .eventNumber: 10

- eventType: studentEnrolled
  studentId: m4242
  courseName: modeling
  lecturerName: Albert
  date: "2019-03-19"
  .eventNumber: 11

