- eventType: buildStudentOffice
  name: FB16
  .eventKey: buildStudentOffice
  .eventNumber: 1

- eventType: buildStudyProgram
  name: CS
  .eventNumber: 2

- eventType: buildCourse
  programName: CS
  name: math
  .eventNumber: 3

- eventType: buildCourse
  programName: CS
  name: modeling
  .eventNumber: 4

- eventType: buildLecturer
  name: Albert
  .eventNumber: 5

- eventType: buildExamination
  course: modeling
  lecturer: Albert
  date: "2019-03-19"
  .eventNumber: 6

- eventType: buildStudent
  studentId: m2323
  name: Bob
  .eventKey: "buildStudent/m2323"
  .eventNumber: 8

- eventType: buildStudent
  studentId: m4242
  name: Alice
  .eventKey: "buildStudent/m4242"
  .eventNumber: 9

- eventType: chooseMajorSubject
  studentId: m4242
  majorSubject: CS
  .eventNumber: 10

- eventType: studentEnrolled
  studentId: m4242
  courseName: modeling
  lecturerName: Albert
  date: "2019-03-19"
  .eventNumber: 11

